# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_adaptive.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.btnGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerate.setObjectName("btnGenerate")
        self.gridLayout.addWidget(self.btnGenerate, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 7, 0, 1, 1)
        self.etInput = QtWidgets.QTextEdit(self.centralwidget)
        self.etInput.setObjectName("etInput")
        self.gridLayout.addWidget(self.etInput, 4, 0, 1, 2)
        self.etOutput = QtWidgets.QTextEdit(self.centralwidget)
        self.etOutput.setObjectName("etOutput")
        self.gridLayout.addWidget(self.etOutput, 9, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tvModelPath = QtWidgets.QLineEdit(self.centralwidget)
        self.tvModelPath.setObjectName("tvModelPath")
        self.horizontalLayout_2.addWidget(self.tvModelPath)
        self.btnChoseModel = QtWidgets.QPushButton(self.centralwidget)
        self.btnChoseModel.setObjectName("btnChoseModel")
        self.horizontalLayout_2.addWidget(self.btnChoseModel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.etOutput.raise_()
        self.etInput.raise_()
        self.label_2.raise_()
        self.btnGenerate.raise_()
        self.label.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Путь до модели"))
        self.btnGenerate.setText(_translate("MainWindow", "Сгенерировать"))
        self.label.setText(_translate("MainWindow", "Введите начальный текст"))
        self.label_2.setText(_translate("MainWindow", "Сгенерированный текст"))
        self.btnChoseModel.setText(_translate("MainWindow", "Выбрать модель"))
